// @author Chong Zhang.
// Please contact me at chongzhang.nc@gmail.com if you have any questions

d3.realtimeLineChart=function(){function c(a){a.each(function(A){var b=c.base.config;g=b.xScale;n=b.yScale;e||(e=b.width);h||(h=b.height);var r=b.margin.top+b.dimension.chartTitle,m=h-r-b.margin.bottom-b.dimension.chartTitle-b.dimension.xTitle-b.dimension.xAxis,f=e-b.margin.left-b.margin.right;t=a.append("svg").attr("width",e).attr("height",h);var d=t.append("g").attr("transform","translate ("+b.margin.left+","+r+")").attr("class","mlineChart");d.append("defs").append("clipPath").attr("id","myClip").append("rect").attr("x",
0).attr("y",0).attr("width",f).attr("height",m);d.append("rect").attr("x",0).attr("y",0).attr("width",f).attr("height",m).attr("class","background");r=d.append("g").attr("class","multiSeries").attr("transform","translate(0, 0)").attr("clip-path","url(#myClip)").append("g");g=d3.time.scale().domain([k-(v-l),k]).range([0,f]);n=d3.scale.linear().domain(w).range([m,0]);q=d.append("g").attr("class","x axis").attr("transform","translate(0,"+m+")").call(g.axis=d3.svg.axis().scale(g).orient("bottom"));x=
d.append("g").attr("class","y axis").call(n.axis=d3.svg.axis().scale(n).orient("left"));q.append("text").attr("class","axisTitle").attr("x",f/2).attr("y",25).attr("dy","1em").text(function(a){return void 0==b.xTitle?"":b.xTitle});x.append("text").attr("class","axisTitle").attr("transform","rotate(-90)").attr("x",-m/2).attr("y",-b.margin.left).attr("text-anchor","middle").attr("dy","1em").text(function(a){return void 0==b.yTitle?"":b.yTitle});m=d.append("text").attr("class","chartTitle").attr("y",
-20).attr("dy",".71em").attr("text-anchor","start").text(function(a){return void 0==b.chartTitle?"":b.chartTitle});m.attr("x",(f-m.node().getComputedTextLength())/2);p=A||[];y=r.append("path").attr("class","movingline");c.refresh()})}var f=6E4,l=6E3,u=30,v=l*u,w=[0,120],q,x,k=Date.now()-f,d=null,p,z,e,h,t,y,B=d3.svg.line().interpolate("basis").x(function(a){return g(a.time)}).y(function(a){return n(a.value)}),g,n;c.updateSize=function(){t.attr("width",e).attr("height",h);var a=c.base.config,d=h-(a.margin.top+
a.dimension.chartTitle)-a.margin.bottom-a.dimension.chartTitle-a.dimension.xTitle-a.dimension.xAxis,a=e-a.margin.left-a.margin.right,b=t.select(".mlineChart");b.select("#myClip rect").attr("width",a).attr("height",d);b.select(".background").attr("width",a).attr("height",d);g.range([0,a]);n.range([d,0]);q.select(".axisTitle").attr("x",a/2);b=b.select(".chartTitle");b.attr("x",(a-b.node().getComputedTextLength())/2);q.attr("transform","translate(0,"+d+")").call(g.axis);x.select(".axisTitle").attr("x",
-d/2).call(n.axis)};c.refresh=function(){k+=l;Date.now()-f-k>f&&(k=Date.now()-f,k+=l);var a=k-(v-l),e=k;p=d?d.history.map(function(a){return{time:a.t,value:a.reportDelay}}).slice(0):[];p.map(function(a){var b=new Date(a.time);return{time:b.getHours()+":"+b.getMinutes()+":"+b.getSeconds(),value:a.value}});y.datum(p).attr("d",B).style("stroke",d?d.color:null);g.domain([a,e]);q.transition().duration(l).ease("linear").call(g.axis);y.attr("transform",null).transition().duration(l).ease("linear").attr("transform",
"translate("+g(k-v)+")").each("end",c.refresh);p.length>u&&p.shift()};c.initialData=function(a){if(!arguments.length)return z;z=a;return this};c.inspectedVehicle=function(a){if(!arguments.length)return d;d=a;return this};c.resize=function(a,c){if(!arguments.length)return this;e=a||e;h=c||h;this.updateSize();return this};c.width=function(a){if(!arguments.length)return e;e=+_x;return this};c.height=function(a){if(!arguments.length)return h;h=+a;return this};c.yDomain=function(a){if(!arguments.length)return w;
w=a;return this};c.duration=function(a){if(!arguments.length)return l;l=a;return this};c.longestHistoryLength=function(a){if(!arguments.length)return u;u=a;return this};c.backTrack=function(a){if(!arguments.length)return f;f=a;return this};c.tick=function(){mlChart.refresh();return this};c.base=baseLineChart();return d3.rebind(c,c.base,"width","height","margin","chartTitle","yTitle","xTitle","dimension","xScale","yScale")};
