// @author Chong Zhang.
// Please contact me at chongzhang.nc@gmail.com if you have any questions


d3.treeChart=function(){function e(a){a.each(function(b){f=b;b=h+g.left+g.right;n=a.append("svg").attr("width",b);k=n.append("g").attr("class","expTree").attr("transform","translate("+g.left+","+g.top+")");r=k.append("rect").attr("width",h+g.left+g.right).attr("class","background");f.x0=0;f.y0=0;f.children.forEach(function(a){a.children.sort(function(a,b){return a.tag<b.tag?-1:a.tag>b.tag?1:0})});f.children.forEach(p);l(f)})}function t(a,b){if(2>a.depth)for(var c=a.hasOwnProperty("children")?"children":
"_children",c=a[c],d=0;d<c.length;d++)t(c[d],b);else b.push(a)}var h=430,q=410,g={top:-10,bottom:10,left:5,right:10},v=0,w=d3.layout.tree().nodeSize([0,20]),f,n,r,k,m=d3.dispatch("nodeClick");m.on("nodeClick.int",function(a){a.checked=!a.checked;if(a.children)for(var b in a.children)a.children[b].checked=a.checked;else if(a._children)for(b in a._children)a._children[b].checked=a.checked;l(a)});m.on("nodeClick.ext");var p=function(a){a.hasOwnProperty("checked")||(a.checked=!1);a.children?(a.numOfChildren=
a.children.length,a._children=a.children,a._children.forEach(p),a.children=null):a.numOfChildren=0},l=function(a){var b=w.nodes(f),c=Math.max(q,30*b.length+g.top+g.bottom);n.transition().duration(200).attr("height",c);r.attr("height",c);b.forEach(function(a,b){a.x=30*b});var c=k.selectAll(".node").data(b.filter(function(a){return"root"!=a.type}),function(a){return a.index||(a.index=++v)}),d=c.enter().append("g").attr("class",function(a){return"node "+a.type}).style("opacity",.001).attr("transform",
function(x){return"translate("+a.y0+","+a.x0+")"});d.filter(function(a){return"route"==a.type}).attr("class",function(a){return d3.select(this).attr("class")+" tag"+a.tag});d.append("path").filter(function(a){return 0<a.numOfChildren&&a.id!=f.id}).attr("d","M-6,-8 L-6,8 L4,0 Z").attr("class","arrow").attr("id",function(a){return"arrow_"+a.name}).attr("transform","translate(-12, 0)").on("click",u);c.select("path").attr("transform",function(a){return a.children?"translate(-12, 0)rotate(90)":"translate(-12, 0)rotate(0)"});
var e=d.append("g").attr("class","mainNode").on("click",m.nodeClick);e.append("rect").attr("width",16).attr("height",16).attr("y",-5);e.select("rect").style("fill",function(a){return a.color});e.append("path").filter(function(a){return a.parent}).attr("class","checkbox uncheck").attr("d","M-8,-8 L-8,8 L8,8 L8,-8 Z M-8,-8 L8,8 M-8,8 L8,-8").attr("transform","translate(8, 2)");c.selectAll(".checkbox").classed("uncheck",function(a){return a.checked?!1:!0});e.filter(function(a){return"group"==a.type}).append("text").attr("dy",
10).attr("dx",18).attr("class","tag").text(function(a){return a.name}).each(function(a){a.tagWidth=d3.select(this).node().getComputedTextLength()});e.filter(function(a){return"route"==a.type}).append("text").attr("dy",10).attr("dx",18).attr("class","title").text(function(a){return a.title}).each(function(a){a.titleWidth=d3.select(this).node().getComputedTextLength()});e.insert("rect","text").attr("height",16).attr("width",function(a){return a.titleWidth}).attr("x",18).attr("y",-4).attr("class","outline").style("stroke",
function(a){return a.color});d.transition().duration(200).attr("transform",function(a){return"translate("+a.y+","+a.x+")"}).style("opacity",1);c.transition().duration(200).attr("transform",function(a){return"translate("+a.y+","+a.x+")"}).style("opacity",1).select("rect");c.exit().transition().duration(200).attr("transform",function(b){return"translate("+a.y+","+a.x+")"}).style("opacity",1E-6).remove();b.forEach(function(a){a.x0=a.x;a.y0=a.y})},u=function(a){a.children?(d3.select("#arrow_"+a.name).attr("translate(-12, 0)rotate(90)"),
a._children=a.children,a.children=null):a._children&&(a.children=a._children,a._children=null);l(a)};e.toggleLeaf=function(a){var b=null;a=isNaN(a.substr(0,1))?"A-Z":a.substr(0,1);for(var c=0;c<f.children.length;c++){var d=f.children[c];d.name==a&&(b=d)}b&&(this.collapseAllNodes(),u(b));return this};e.highlightLeaf=function(a){k.select(".tag"+a).select(".outline").transition().duration(4E3).styleTween("fill",function(){return d3.interpolateRgb("yellow","white")}).each("end",function(){d3.select(this).style("fill",
null)})};e.collapseAllNodes=function(){f.children.forEach(p);l(f);return this};e.getAllLeafNodes=function(){var a=[];t(f,a);return a};e.getUncheckedNodes=function(){for(var a=[],b=this.getAllLeafNodes(),c=0;c<b.length;c++){var d=b[c];d.checked||a.push({name:d.name,tag:d.tag,title:d.title})}return a};e.width=function(a){if(!arguments.length)return h;h=a;return this};e.height=function(a){if(!arguments.length)return q;q=a;return this};return d3.rebind(e,m,"on")};
