// based on ArcGIS API for JavaScript 3.30
// @author Chong Zhang.
// Please contact me at chongzhang.nc@gmail.com if you have any questions
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(h){var k=0;return function(){return k<h.length?{done:!1,value:h[k++]}:{done:!0}}};$jscomp.arrayIterator=function(h){return{next:$jscomp.arrayIteratorImpl(h)}};$jscomp.makeIterator=function(h){var k="undefined"!=typeof Symbol&&Symbol.iterator&&h[Symbol.iterator];return k?k.call(h):$jscomp.arrayIterator(h)};
define("dojo/_base/declare esri/geometry/Point dojo/_base/lang esri/layers/GraphicsLayer esri/geometry/screenUtils esri/geometry/webMercatorUtils /share/js/d3.v4.js".split(" "),function(h,k,l,t,w,u,f){return t.createSubclass({constructor:function(b,d){this.url=b;this.callback=d.callback||function(){};this.svg_type=d.svgType||"path";this.id=d.id||Date.now().toString(16);this._styles=d.style||{};this._attrs=d.attr||{};this._svg_layer_sel="#"+this.id+"_layer";var c=d.colorScale0||"#feebe2",e=d.colorScale1||
"#dd1c77";this.colorScale=f.scaleLinear().range([c,e]);this.secell=32;this.unitRadius=4;this.rawPoints=d.rawPoints;this._parentMap=d.parentMap;this.curLOD=d.LOD||0;this._LOD=[0,1,2,3,4,5];this._LOD2Depth=[4,5,6,7,8,9];this._zoom2LOD=d.zoom2LOD||{10:[1,2,3,4,5,6,7],11:[2,3,4,5,6,7],12:[3,4,5,6,7,8],13:[4,5,6,7,8],14:[5,6,7,8,9],15:[6,7,8,9],16:[8,9,10]}},_setMap:function(b,d){var c=this;this.curZoom=b.getZoom();f.json(c.url,function(b){c.geoFeatures=b;c.bbox=f.geoBounds(b);c.loaded=!0;c._render();
c.onLoad(c);c.callback(b);c._map.container.style.left&&(b=[-c._map.container.offsetLeft,-c._map.container.offsetTop],c.getSVGFeatureGroupSelection().attr("transform","translate("+b[0]+","+b[1]+")"));c.initTranslate=[-c._map.container.offsetLeft,-c._map.container.offsetTop]});this.mapWidth=b.width;this.mapHeight=b.height;this._parentMap&&(this.parentMapWidth=this._parentMap.width,this.parentMapHeight=this._parentMap.height);this._redraw=b.on("zoom-end",l.hitch(this,function(b){this.rawPoints||(this.startClusterPerZoom=
this._initClusteringArray(this.geoFeatures.features),this._createQuadTree(),this.restoreStatus||(this.curLOD+=1),this.restoreStatus=!1);this.redraw()}));b.on("click",l.hitch(this,function(b){b=this._map.getZoom();b=this._zoom2LOD[b];this.curLOD!==b[b.length-1]?(this.curLOD+=1,this.setVisibility(!0),this.redraw()):(this.setVisibility(!1),this.curLOD=b[0])}));this._path_draw=f.geoPath().projection(f.geoMercator().scale((this.mapWidth+1)/2/Math.PI).translate([this.mapWidth/2,this.mapHeight/2]).precision(.1));
return this.inherited(arguments)},_unsetMap:function(){this.inherited(arguments);this._redraw.remove()},resetCenter:function(){this.getSVGFeatureGroupSelection().attr("transform","translate("+this.initTranslate[0]+","+this.initTranslate[1]+")")},attr:function(b){("data-suspended"!=b||this.suspended)&&this.getSVGFeatureSelections().attr(b.key,b.value);return this.inherited(arguments)},restore:function(b,d){this.restoreStatus=!0;this.curLOD=d;var c=this._zoom2LOD[b];b!==this._map.getZoom()&&(this.startClusterPerZoom=
null,this._createQuadTree());d!==c[c.length-1]?(this.setVisibility(!0),this.redraw()):this.setVisibility(!1)},_createQuadTree:function(){this.startClusterPerZoom||(this.startClusterPerZoom=this._initClusteringArray(this.geoFeatures.features));this.quadtree=f.quadtree().x(function(b){return b.x}).y(function(b){return b.y}).addAll(this.startClusterPerZoom)},_render:function(){var b=this._map.getZoom(),d;this.rawPoints||(d=this._zoom2LOD[b]);var c=this,e=this.getSVGFeatureGroupSelection();if(this.rawPoints){e=
e.selectAll("circle").data(this.geoFeatures.features).enter().append(this.svg_type).attr("r",function(a){return a.r});"path"!==this.svg_type&&e.attr("transform",function(a){return"translate("+c._project_to_screen1(a.geometry.coordinates)[0]+","+c._project_to_screen1(a.geometry.coordinates)[1]+")"});for(attrName in this._attrs)e.attr(attrName,this._attrs[attrName]);e.attr("class",function(a,b){return f.select(this).attr("class")+" "+c.id});for(styleName in this._styles)e.style(styleName,this._styles[styleName])}else if(this.quadtree||
this._createQuadTree(),this.quadtreeNodes=this._nodes(this.quadtree),this.curLOD===d[1]){b=this.clustering(this.quadtree);e=e.selectAll("circle").data(b,function(a){return a?c.curLOD+1+"_"+Math.floor(a.x)+"_"+Math.floor(a.y)+"_"+a.r+"_"+a.index:"null"});e.attr("transform",function(a){return"translate("+a.x+","+a.y+")"}).attr("r",function(a){return a.r});b=e.enter().append("circle").attr("transform",function(a){return"translate("+a.x+","+a.y+")"}).attr("r",function(a){return a.r});for(attrName in this._attrs)b.attr(attrName,
this._attrs[attrName]);b.attr("class",function(a,b){return f.select(this).attr("class")+" cluster "});for(styleName in this._styles)b.style(styleName,this._styles[styleName]);e.exit().remove()}else if(this.curLOD===d[0])this.setVisibility(!1),this.visible=!1;else{d=c.quadtreeNodes.filter(function(a){return 0<a.size&&128>a.width});b=this._getNextLevelQuadLeaves(d,this.curLOD,b);d=[];var g=f.extent(b,function(a){return a.size}),v=f.extent(d,function(a){return a.size});g=f.extent(g.concat(v));c.colorScale.domain(g);
e.selectAll(".leafGrid").data(b,function(a){return a.depth+"_"+a.x+"_"+a.y}).enter().append("rect").attr("class","leafGrid").attr("x",function(a){return a.x}).attr("y",function(a){return a.y}).attr("width",function(a){return a.width}).attr("height",function(a){return a.height}).style("fill",function(a){return c.colorScale(a.size)});e.selectAll(".upperGrid").data(d,function(a){return a.depth+"_"+a.x+"_"+a.y}).enter().append("rect").attr("class","upperGrid").attr("x",function(a){return a.x}).attr("y",
function(a){return a.y}).attr("width",function(a){return a.width}).attr("height",function(a){return a.height}).style("fill",function(a){return c.colorScale(a.size)})}},_nodes:function(b){b.root().depth=0;b.visitAfter(function(b){return null==b.length?b.size=1:b.size=f.sum(b,function(b){return null!=b?b.size:0})});var d=[];b.visit(function(b,e,g,f,a){b.hasChild=!1;for(var c=0;4>c;c++)b[c]&&(b[c].depth=b.depth+1,b.hasChild=!0);d.push({x:e,y:g,width:f-e,height:a-g,size:b.size,depth:b.depth,hasChild:b.hasChild})});
return d},redraw:function(){var b=this._map.getZoom(),d=this,c=this.getSVGFeatureGroupSelection();if(this.curZoom!==b&&(this.curZoom=b,d._map.container.offsetLeft)){var e=-1*+d._map.container.offsetLeft,g=-1*+d._map.container.offsetTop;d.getSVGFeatureGroupSelection().attr("transform","translate("+e+","+g+")")}if(this.rawPoints)"path"!=this.svg_type&&c.selectAll("circle").attr("transform",function(a){return"translate("+d._project_to_screen1(a.geometry.coordinates)[0]+","+d._project_to_screen1(a.geometry.coordinates)[1]+
")"});else if("path"!=this.svg_type)if(e=this._zoom2LOD[b],this.quadtree||this._createQuadTree(),this.curLOD===e[1]){c.selectAll("rect").remove();b=this.clustering(this.quadtree);this.quadtree.display="circle";this.quadtreeNodes=this._nodes(this.quadtree);c=c.selectAll("circle").data(b,function(a){return a?d.curLOD+1+"_"+Math.floor(a.x)+"_"+Math.floor(a.y)+"_"+a.r+"_"+a.index:"null"});c.attr("transform",function(a){return"translate("+a.x+","+a.y+")"}).attr("r",function(a){return a.r});b=c.enter().append("circle").attr("transform",
function(a){return"translate("+a.x+","+a.y+")"}).attr("r",function(a){return a.r});for(attrName in this._attrs)b.attr(attrName,this._attrs[attrName]);b.attr("class",function(a,b){return f.select(this).attr("class")+" cluster "});for(styleName in this._styles)b.style(styleName,this._styles[styleName]);c.exit().remove()}else{this.quadtree.display="rect";this.quadtreeNodes=this._nodes(this.quadtree);c.selectAll("circle").remove();e=this.quadtreeNodes.filter(function(a){return 0<a.size&&128>a.width});
e=this._getNextLevelQuadLeaves(e,d.curLOD,b);b=[];g=f.extent(e,function(a){return a.size});var h=f.extent(b,function(a){return a.size});g=f.extent(g.concat(h));d.colorScale.domain(g);e=c.selectAll(".leafGrid").data(e,function(a){return a.depth+"_"+a.x+"_"+a.y+"_"+a.width});e.exit().remove();e.enter().append("rect").attr("class","leafGrid").attr("x",function(a){return a.x}).attr("y",function(a){return a.y}).attr("width",function(a){return a.width}).attr("height",function(a){return a.height}).style("fill",
function(a){return d.colorScale(a.size)});c=c.selectAll(".upperGrid").data(b,function(a){return a.depth+"_"+a.x+"_"+a.y+"_"+a.width});c.exit().remove();c.enter().append("rect").attr("class","upperGrid").attr("x",function(a){return a.x}).attr("y",function(a){return a.y}).attr("width",function(a){return a.width}).attr("height",function(a){return a.height}).style("fill",function(a){return d.colorScale(a.size)})}else this.getSVGFeatureSelections().attr("d",d._path_draw)},_getNextLevelQuadLeaves:function(b,
d,c){return b.filter(function(b){return b.depth===d})},getSVGLayerSelector:function(){return this._svg_layer_sel},getSVGFeatureSelections:function(){return f.select(this._svg_layer_sel).selectAll(this.svg_type)},getSVGFeatureGroupSelection:function(){return f.select(this._svg_layer_sel).select("g")},_project_to_screen1:function(b){b=new k(b[0],b[1]);b=this._map.toScreen(b);return[b.x,b.y]},_project_to_screen:function(b){b=u.lngLatToXY(b[0],b[1]);b=this._parentMap.toScreen({x:b[0],y:b[1]});return[b.x,
b.y]},_initClusteringArray:function(b){var d=this;return b.map(function(b,e){var c=d._project_to_screen(b.geometry.coordinates);return{x:c[0],y:c[1],r:d.unitRadius,points:[Object.assign({},b,{scrCoordinates:c})]}})},_averageClusters:function(b,d){var c=d.r/(b.r+d.r);return{x:b.x+c*(d.x-b.x),y:b.y+c*(d.y-b.y),r:this.unitRadius*Math.log(b.points.length+d.points.length)*2,points:b.points.concat(d.points)}},clustering:function(b){function d(a,b,c,d,e){var r=[];a.visit(function(a,f,g,h,k){if(a=a.data)a.selected=
a.x>=b&&a.x<d&&a.y>=c&&a.y<e,a.selected&&r.push(a);return f>=d||g>=e||h<b||k<c});return r}var c=this,e=[],g=$jscomp.makeIterator(b.extent()),h=$jscomp.makeIterator(g.next().value),a=h.next().value;h=h.next().value;var k=$jscomp.makeIterator(g.next().value);g=k.next().value;for(k=k.next().value;a<=g;a+=c.secell)for(var m=h;m<=k;m+=c.secell){var l=d(b,a,m,a+c.secell,m+c.secell);l.length&&e.push(l.reduce(c._averageClusters.bind(c)))}var n=f.max(e,function(a){return a.r}),p=!0;for(e.map(function(a,b){a.index=
b;return a});p;){p=!1;var q=[];f.voronoi().x(function(a){return a.x+Math.random()-.5}).y(function(a){return a.y+Math.random()-.5}).links(e.filter(function(a){return!!a})).map(function(a){var b=a.source.x-a.target.x,c=a.source.y-a.target.y;a.distance=Math.sqrt(b*b+c*c);q.push(a)});q.sort(function(a,b){return a.distance-b.distance});q.every(function(a){if(a.distance>2*n)return!1;if(a.distance<a.source.r+a.target.r){p=!0;var b=c._averageClusters(a.source,a.target);b.index=a.source.index;e[a.target.index]=
null;e[a.source.index]=b;n=Math.max(n,b.r);return!1}return!0})}return e.filter(function(a){return null!==a})}})});
